### ISSUE TITLE
it fails for Wikidata entries with "author" fields

### ISSUE THREAD

**Issue by egonw** [larsgw/citation.js#19]
E.g. for https://www.wikidata.org/wiki/Q27795847 where it fails with this message:

    Uncaught TypeError: str.split is not a function
        at parseName (https://larsgw.github.io/citation.js/src/citation-0.2.js:415:19)
        at https://larsgw.github.io/citation.js/src/citation-0.2.js:1014:54
        at Array.map (native)
        at parseWikidataProp (https://larsgw.github.io/citation.js/src/citation-0.2.js:1014:22)
        at parseWikidataJSON (https://larsgw.github.io/citation.js/src/citation-0.2.js:1179:18)
        at parseInputData (https://larsgw.github.io/citation.js/src/citation-0.2.js:1793:16)
        at parseInput (https://larsgw.github.io/citation.js/src/citation-0.2.js:1835:14)
        at parseInputData (https://larsgw.github.io/citation.js/src/citation-0.2.js:1765:16)
        at parseInput (https://larsgw.github.io/citation.js/src/citation-0.2.js:1835:14)
        at Cite.add (https://larsgw.github.io/citation.js/src/citation-0.2.js:2176:17)

**Comment by larsgw** [comment]
Apparently, I didn't run enough tests after adding the P50 property. It will be fixed in `v0.2.12` and appropriate tests will be added in the same version or in `v0.3`, as there is a test case shortage (#22)
